

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class Calculadora extends javax.swing.JFrame {
    double operando1, operando2, resultado;
    char operador;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boton2 = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        pantalla = new javax.swing.JTextField();
        botonpunto = new javax.swing.JButton();
        botonce = new javax.swing.JButton();
        botonc = new javax.swing.JButton();
        botonmas = new javax.swing.JButton();
        botonmenos = new javax.swing.JButton();
        botonpor = new javax.swing.JButton();
        botondiv = new javax.swing.JButton();
        botonigua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 195, 195));
        jPanel1.setLayout(null);

        boton2.setBackground(new java.awt.Color(233, 214, 176));
        boton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton2.setForeground(new java.awt.Color(155, 118, 80));
        boton2.setText("2");
        boton2.setMaximumSize(new java.awt.Dimension(80, 50));
        boton2.setMinimumSize(new java.awt.Dimension(80, 50));
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        jPanel1.add(boton2);
        boton2.setBounds(120, 80, 80, 50);

        boton1.setBackground(new java.awt.Color(233, 214, 176));
        boton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton1.setForeground(new java.awt.Color(155, 118, 80));
        boton1.setText("1");
        boton1.setMaximumSize(new java.awt.Dimension(80, 50));
        boton1.setMinimumSize(new java.awt.Dimension(80, 50));
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        jPanel1.add(boton1);
        boton1.setBounds(20, 80, 80, 50);

        boton3.setBackground(new java.awt.Color(233, 214, 176));
        boton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton3.setForeground(new java.awt.Color(155, 118, 80));
        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        jPanel1.add(boton3);
        boton3.setBounds(220, 80, 80, 50);

        boton4.setBackground(new java.awt.Color(233, 214, 176));
        boton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton4.setForeground(new java.awt.Color(155, 118, 80));
        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        jPanel1.add(boton4);
        boton4.setBounds(20, 150, 80, 50);

        boton5.setBackground(new java.awt.Color(233, 214, 176));
        boton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton5.setForeground(new java.awt.Color(155, 118, 80));
        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        jPanel1.add(boton5);
        boton5.setBounds(120, 150, 80, 50);

        boton6.setBackground(new java.awt.Color(233, 214, 176));
        boton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton6.setForeground(new java.awt.Color(155, 118, 80));
        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        jPanel1.add(boton6);
        boton6.setBounds(220, 150, 80, 50);

        boton7.setBackground(new java.awt.Color(233, 214, 176));
        boton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton7.setForeground(new java.awt.Color(155, 118, 80));
        boton7.setText("7");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        jPanel1.add(boton7);
        boton7.setBounds(20, 220, 80, 50);

        boton8.setBackground(new java.awt.Color(233, 214, 176));
        boton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton8.setForeground(new java.awt.Color(155, 118, 80));
        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });
        jPanel1.add(boton8);
        boton8.setBounds(120, 220, 80, 50);

        boton9.setBackground(new java.awt.Color(233, 214, 176));
        boton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton9.setForeground(new java.awt.Color(155, 118, 80));
        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });
        jPanel1.add(boton9);
        boton9.setBounds(220, 220, 80, 50);

        boton0.setBackground(new java.awt.Color(233, 214, 176));
        boton0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton0.setForeground(new java.awt.Color(155, 118, 80));
        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });
        jPanel1.add(boton0);
        boton0.setBounds(20, 290, 180, 50);

        pantalla.setEditable(false);
        pantalla.setBackground(new java.awt.Color(225, 255, 225));
        pantalla.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantallaActionPerformed(evt);
            }
        });
        jPanel1.add(pantalla);
        pantalla.setBounds(20, 20, 440, 40);

        botonpunto.setBackground(new java.awt.Color(233, 214, 176));
        botonpunto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonpunto.setForeground(new java.awt.Color(155, 118, 80));
        botonpunto.setText(".");
        botonpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonpuntoActionPerformed(evt);
            }
        });
        jPanel1.add(botonpunto);
        botonpunto.setBounds(220, 290, 80, 50);

        botonce.setBackground(new java.awt.Color(255, 132, 132));
        botonce.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonce.setForeground(new java.awt.Color(155, 118, 80));
        botonce.setText("CE");
        botonce.setBorder(null);
        botonce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonceActionPerformed(evt);
            }
        });
        jPanel1.add(botonce);
        botonce.setBounds(320, 80, 65, 50);

        botonc.setBackground(new java.awt.Color(255, 132, 132));
        botonc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonc.setForeground(new java.awt.Color(155, 118, 80));
        botonc.setText("C");
        botonc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncActionPerformed(evt);
            }
        });
        jPanel1.add(botonc);
        botonc.setBounds(400, 80, 65, 50);

        botonmas.setBackground(new java.awt.Color(255, 153, 153));
        botonmas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonmas.setForeground(new java.awt.Color(155, 118, 80));
        botonmas.setText("+");
        botonmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmasActionPerformed(evt);
            }
        });
        jPanel1.add(botonmas);
        botonmas.setBounds(320, 150, 65, 50);

        botonmenos.setBackground(new java.awt.Color(255, 153, 153));
        botonmenos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonmenos.setForeground(new java.awt.Color(155, 118, 80));
        botonmenos.setText("-");
        botonmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmenosActionPerformed(evt);
            }
        });
        jPanel1.add(botonmenos);
        botonmenos.setBounds(400, 150, 65, 50);

        botonpor.setBackground(new java.awt.Color(255, 153, 153));
        botonpor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonpor.setForeground(new java.awt.Color(155, 118, 80));
        botonpor.setText("*");
        botonpor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonporActionPerformed(evt);
            }
        });
        jPanel1.add(botonpor);
        botonpor.setBounds(320, 220, 65, 50);

        botondiv.setBackground(new java.awt.Color(255, 153, 153));
        botondiv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botondiv.setForeground(new java.awt.Color(155, 118, 80));
        botondiv.setText("/");
        botondiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondivActionPerformed(evt);
            }
        });
        jPanel1.add(botondiv);
        botondiv.setBounds(320, 290, 65, 50);

        botonigua.setBackground(new java.awt.Color(255, 153, 153));
        botonigua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonigua.setForeground(new java.awt.Color(155, 118, 80));
        botonigua.setText("=");
        botonigua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoniguaActionPerformed(evt);
            }
        });
        jPanel1.add(botonigua);
        botonigua.setBounds(400, 220, 65, 120);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 470, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText()+"1");

    }//GEN-LAST:event_boton1ActionPerformed

    private void pantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pantallaActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText()+"9");

    }//GEN-LAST:event_boton9ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText()+"2");

    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText()+"3");

    }//GEN-LAST:event_boton3ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText()+"4");

    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText()+"5");

    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText()+"6");

    }//GEN-LAST:event_boton6ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText()+"8");

    }//GEN-LAST:event_boton8ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText()+"7");

    }//GEN-LAST:event_boton7ActionPerformed

    private void botonpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonpuntoActionPerformed
        // TODO add your handling code here:
        boolean hayPunto= false;
 for(int i=0; i<pantalla.getText().length();i++){
 if(pantalla.getText().charAt(i)=='.'){
 hayPunto=true;
 break;}
 }
 if(!hayPunto){
 pantalla.setText(pantalla.getText()+'.');
 }

    }//GEN-LAST:event_botonpuntoActionPerformed

    private void botonceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonceActionPerformed
        // TODO add your handling code here:
        if(pantalla.getText().length()>0){
 pantalla.setText(pantalla.getText().substring(0,pantalla.getText().length()-1));
 }
    }//GEN-LAST:event_botonceActionPerformed

    private void botoncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncActionPerformed
        // TODO add your handling code here:
        pantalla.setText("");
    }//GEN-LAST:event_botoncActionPerformed

    private void botonmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmasActionPerformed
        // TODO add your handling code here:
        if(pantalla.getText().length()>0){
 operando1=Double.parseDouble(pantalla.getText());
 operador='+';
 pantalla.setText("");
 }
    }//GEN-LAST:event_botonmasActionPerformed

    private void botonmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmenosActionPerformed
        // TODO add your handling code here:
        if(pantalla.getText().length()>0){
 operando1=Double.parseDouble(pantalla.getText());
 operador='-';
 pantalla.setText("");
 }
    }//GEN-LAST:event_botonmenosActionPerformed

    private void botonporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonporActionPerformed
        // TODO add your handling code here:
        if(pantalla.getText().length()>0){
 operando1=Double.parseDouble(pantalla.getText());
 operador='*';
 pantalla.setText("");
 }
    }//GEN-LAST:event_botonporActionPerformed

    private void botondivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondivActionPerformed
        // TODO add your handling code here:
        if(pantalla.getText().length()>0){
 operando1=Double.parseDouble(pantalla.getText());
 operador='/';
 pantalla.setText("");
 }
    }//GEN-LAST:event_botondivActionPerformed

    private void botoniguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoniguaActionPerformed
        // TODO add your handling code here:
        if(pantalla.getText().length()>0){
 operando2=Double.parseDouble(pantalla.getText());
 switch(operador){
 case '+':
 resultado= operando1+operando2;
 pantalla.setText(Double.toString(resultado));
 break;
 case '-':
 resultado= operando1-operando2;
 pantalla.setText(Double.toString(resultado));
 break;
 case '*':
 resultado= operando1*operando2;
 pantalla.setText(Double.toString(resultado));
 break;
 case '/':
 resultado= operando1/operando2;
 pantalla.setText(Double.toString(resultado));
 break;

 }
}
    }//GEN-LAST:event_botoniguaActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText()+"0");
    }//GEN-LAST:event_boton0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonc;
    private javax.swing.JButton botonce;
    private javax.swing.JButton botondiv;
    private javax.swing.JButton botonigua;
    private javax.swing.JButton botonmas;
    private javax.swing.JButton botonmenos;
    private javax.swing.JButton botonpor;
    private javax.swing.JButton botonpunto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pantalla;
    // End of variables declaration//GEN-END:variables
}
